[build]
  command = "python my_build_script.py"
  command = "npm run build"
  publish = "frontend/dist"
  functions = "functions"
  node_version = "14"
  python_version = "3.8" 
  runtime = "python3.8"
  region = "us-east-1"
  role = "arn:aws:iam::1234567890
  :role/lambda-existing-execution-role"
  environment = {
    "AWS_REGION": "us-east-1",
    "AWS_EXECUTION_ENV": "AWS_Lambda_python3.9"
    "AWS_LAMBDA_FUNCTION_NAME": "my_function"
  }

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

